# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-06 10:17
from __future__ import unicode_literals

import FileSaverApp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to=FileSaverApp.models.get_directory_path)),
                ('document_text', models.CharField(default='', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
                ('category_details', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FileSaverApp.Document')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='document_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FileSaverApp.DocumentCategory'),
        ),
    ]
