# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-06 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileSaverApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentcategory',
            name='category_details',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
