# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-11 10:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FileSaverApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='question_text',
            new_name='file_name',
        ),
        migrations.RenameField(
            model_name='keywords',
            old_name='question',
            new_name='document',
        ),
    ]
