# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-11 10:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FileSaverApp', '0002_auto_20171011_1052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keywords',
            old_name='choice_text',
            new_name='keyword',
        ),
    ]
