# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-11 23:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FileSaverApp', '0003_auto_20171011_1054'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Keywords',
            new_name='Keyword',
        ),
    ]
