# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-11 23:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FileSaverApp', '0004_auto_20171011_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='votes',
        ),
    ]
