# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-28 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileSaverApp', '0005_remove_keyword_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
