# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-16 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileSaverApp', '0006_document_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_path',
            field=models.CharField(default='pdfs/', max_length=300),
        ),
        migrations.AddField(
            model_name='document',
            name='file_text',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='document',
            name='file_title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
