# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-16 10:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FileSaverApp', '0007_auto_20171116_0712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='file_name',
            new_name='document_name',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='file_text',
            new_name='document_text',
        ),
        migrations.RemoveField(
            model_name='document',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='document',
            name='file_title',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pub_date',
        ),
    ]
